# Copyright (c) 2019 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: "3"
services:
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - 5672:5672

  mongodb:
    image: "mongo:latest"
    ports:
      - 27017:27017
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
